from oop import Animal,Cat,Mouse,Jorge

name1 = Animal("Гав", "2", "мальчик")
name1.hello()
name1.hi()
name1.goodbye()
cat1 = Cat()
cat1.hello()
cat1.hi()
cat1.goodbye()
cat1.sleep()
mouse1 = Mouse()
mouse1.hello()
mouse1.hi()
mouse1.goodbye()
mouse1.eat()
j1 = Jorge()
j1.hello()
j1.hi()
j1.goodbye()
j1.dead()